config/routes.rb
Rails.application.routes.draw do

  get 'generals/index'

  get 'generals/edit'

  get 'generals/update'

  devise_for :users

  root  'pages#index'
  get 'consulta/:id' => 'pages#consulta'
  resources :cars do
    resources :pictures
  end

  get 'pictures/sort' => 'pictures#sort'

  resources :generals

end

app/views/includes/_menu.erb
<% if user_signed_in? %>

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="index.html">Administrador Sofasa</a>
  </div>
  <!-- Top Menu Items -->
  <ul class="nav navbar-right top-nav">


    <li class="dropdown">
    <%= link_to '<i class="fa fa-user"></i>  Salir'.html_safe,  destroy_user_session_path,  method: :delete, :class=>'dropdown'%>
    </li>
  </ul>
  <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
      <li>
        <a href="<%= cars_path %>"><i class="fa fa-fw fa-dashboard"></i> Vehiculos</a>
      </li>
      <li>
        <a href="<%= generals_path %>"><i class="fa fa-fw fa-bar-chart-o"></i> Generales</a>
      </li>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</nav>

<% end %>