config/routes.rb
Rails.application.routes.draw do

  get 'generals/index'

  get 'generals/edit'

  get 'generals/update'

  devise_for :users

  root  'pages#index'
  get 'consulta/:id' => 'pages#consulta'
  resources :cars do
    resources :pictures
  end

  get 'pictures/sort' => 'pictures#sort'

  resources :generals

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :car



  #has_attached_file :picture1
  #validates_attachment_presence :picture1



  HUMANIZED_ATTRIBUTES = {
      :picture1 => 'Imagen 1',
      :picture2 => 'Imagen 2',
      :time => 'Tiempo'
  }

  def self.human_attribute_name(attr, options = {})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end


  has_attached_file :picture1, :styles => {:home => '548x300>', :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture1, :content_type => /\Aimage\/.*\Z/

  has_attached_file :picture2, :styles => {:home => '548x300>', :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture2, :content_type => /\Aimage\/.*\Z/





  default_scope { order("priority ASC") }

  before_create do

    ultimo = Picture.where(:car_id => self.car_id).last()

    if ultimo.nil?
      self.priority = 1
    else
      self.priority = ultimo.priority+1
    end

  end

  after_destroy do


    pictures = Picture.where(:car_id => self.car_id).all

    puts YAML::dump(pictures)

    numero = 1
    pictures.each do |value|

    Picture.find(value.id).update_attribute(:priority,numero)
    numero = numero +1

    end

  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  def index
    @pictures = Picture.where(car_id: params[:car_id])
    @tiempoGeneral = General.find_by_id(1)
    @car = Car.find(params[:car_id])








  end

  def create



    if params[:picture1]
      # The magic is here ;)
      cuenta = 0;
      params[:picture1].each { |image|
       # @gallery.pictures.create(image: image)
       # @gallery.pictures.create(image: image)



        @car = Picture.find_by_id(params[:car_id])

        @picture = Picture.new(allowed_params)

        @picture.car_id = params[:car_id]
        @picture.picture1 = image
        @picture.picture2 = image
        flash[:notice] = 'Información creada correctamente'
         @picture.save



      }

      redirect_to car_pictures_path(params[:car_id])

    end




#=)








  end

  def new

    @car = Car.find_by_id(params[:car_id])
    @picture = Picture.new(:car_id=>@car)




  end

  def edit
    @car = Car.find_by_id(params[:car_id])
    @picture = Picture.find(params[:id]);
  end

  def update
    @picture = Picture.find(params[:id])

    if @picture.update_attributes(allowed_params)
      flash[:notice] = 'Información actualizada correctamente'
      redirect_to car_pictures_path(params[:car_id])
    else
      render 'new'
    end


  end

  def destroy
    @picture = Picture.find(params[:id])
    if @picture.destroy
      flash[:notice] = 'Información eliminada correctamente'
      redirect_to car_pictures_path(params[:car_id])
    else
      render 'new'
    end
  end


  def sort
    params[:order].each do |key,value|
      Picture.find(value[:id]).update_attribute(:priority,value[:position])
    end
    render :nothing => true
  end


  private
  def allowed_params
    params.require(:picture).permit(:time, :picture1, :picture2, :position1, :position2, :car_id)
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/create.html.erb
<h1>Pictures#create</h1>
<p>Find me in app/views/pictures/create.html.erb</p>

app/views/pictures/destroy.html.erb
<h1>Pictures#destroy</h1>
<p>Find me in app/views/pictures/destroy.html.erb</p>

app/views/pictures/edit.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Imagenes <small>Agregar</small>
        </h1>
      </div>
    </div>
    <!-- /.row -->




    <div class="row">

      <div class="col-lg-12">
        <div class="panel panel-default">

          <div class="panel-body">
            <%= form_for [@car, @picture] do |f|  %>

                <%  if @picture.errors.any? %>
                    <div class="panel panel-danger">
                      <div class="panel-heading">
                        <%= pluralize(@picture.errors.count, "Errores") %> tratando de guardar:
                      </div>
                      <p>
                      <ul>
                        <% @picture.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                      </ul>
                      </p>
                    </div>
                <% end %>


                <div class="row">
                  <div class="col-md-4">
                    <div class="form-group">
                      <%= f.label :time, 'Tiempo' %> / <small>Segundos</small>
                      <%= f.text_field :time, :class =>'form-control required'  %>


                    </div>
                  </div>

                </div>



                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <%= f.label :picture1, 'Imagen 1' %>
                      <%= f.file_field :picture1, :class =>'form-control'  %>
                      <br/>
                      Imagen actual <br/> <br/>
                      <%= image_tag @picture.picture1(:home), :class=>'img-thumbnail', height: "200" %>
                    </div>
                  </div>

                  <div class="col-md-6">
                    <div class="form-group">
                      <%= f.label :picture2, 'Imagen 2' %>
                      <%= f.file_field :picture2, :class =>'form-control' %> <br/>
                      Imagen actual <br/> <br/>
                      <%= image_tag @picture.picture2(:home), :class=>'img-thumbnail', height: "200" %>
                    </div>
                  </div>

                </div>




                <div class="row">
                  <div class="col-md-12">
                    <p>
                      <%= f.submit 'Guardar', :class=> 'btn btn-info' %>
                      <%= link_to 'Cancelar', car_pictures_path(params[:car_id]),  :class=>'btn btn-danger' %>
                    </p>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->

app/views/pictures/index.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Imagenes
        </h1>

      </div>
    </div>
    <!-- /.row -->





    <% if flash[:notice] %>
        <div class="row">
          <div class="col-lg-12">
            <div class="alert alert-info alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= flash[:notice] %>
            </div>
          </div>
        </div>
    <% end %>

    <div class="row">



      <div class="col-lg-12">

            <h3 class="panel-title"><i class="fa fa-car fa-fw"></i> <%= @car.name %> </h3>
            <h4>Tiempo: <%= (Time.mktime(0)+ @tiempoGeneral.value.to_i ).strftime("%M:%S") %> (<%=  @tiempoGeneral.value.to_i  %>'')</h4>
            <%
               @restotiempo =  @tiempoGeneral.value.to_i-@pictures.sum(:time)

               @cuentasi =@pictures.count(:time)
               @cuentano = @pictures.count - @pictures.count(:time)
               if @cuentano == 0
                @cuentano = 1
               end

               @promedio = @restotiempo  / @cuentano

               @mod = @restotiempo  % @cuentano

            %>
            <p>
              <%= @pictures.count %>
              Promedio: <%= @promedio %> <br/>
              Tiempo sobrante: <%= @mod %>
            </p>
          </div>

            <p>

              <%= link_to 'Agregar Imagen', new_car_picture_path,  :class=>'btn btn-info', method: :get %>
            </p>

      <div class="">
        <div class=" sortable">
      <% @pictures.each_with_index do |item, index|  %>
          <div class="panel panel-default" data-id="<%= item.id %>" data-pos="<%= item.priority %>">
            <div class="panel-heading">
              <h3 class="panel-title">


                <div class="row">
                  <div class="col-md-1">
                    <% if !item.time.nil? %>
                        <%= item.time %>''
                    <% else %>
                        <%= @promedio %>''
                    <% end %>
                  </div>
                  <div class="col-md-2 ">
                    <%= image_tag item.picture1(:home), :class=>'img-thumbnail', size: "200x200" %>
                  </div>
                  <div class="col-md-5">
                    <%= image_tag item.picture2(:home), :class=>'img-thumbnail', size: "200x200" %>
                  </div>
                </div>


              </h3>
            </div>
            <div class="panel-body">
              <%= link_to 'Editar', edit_car_picture_path(item.car_id, item.id), :class=>'btn btn-info',method: :get %>
              <%= link_to 'Eliminar', {:controller => 'pictures', :action => 'destroy', :id => item.id}, :data => {:confirm => 'Estas seguro de eliminar este elemento?'}, :method => :delete, :class=>'btn btn-danger' %>



            </div>
          </div>

      <% end %>
        </div>
      </div>



      <table class="table">



            </table>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->



<script>

    var ready, set_positions;

    set_positions = function(){
        // loop through and give each task a data-pos
        // attribute that holds its position in the DOM
        $('.panel.panel-default').each(function(i){
            $(this).attr("data-pos",i+1);
        });
    }

    ready = function(){

        // call set_positions function
        set_positions();

        $('.sortable').sortable();

        // after the order changes
        $('.sortable').sortable().bind('sortupdate', function(e, ui) {
            // array to store new order
            updated_order = []
            // set the updated positions
            set_positions();

            // populate the updated_order array with the new task positions
            $('.panel.panel-default').each(function(i){
                updated_order.push({ id: $(this).data("id"), position: i+1 });
            });


            // send the updated order via ajax
            $.ajax({
                type: "GET",
                url: '<%= pictures_sort_path() %>',
                data: { order: updated_order }
            });
        });
    }

    $(document).ready(ready);
    /**
     * if using turbolinks
     */
    $(document).on('page:load', ready);

</script>

<style>
    .sortable-placeholder {
        border: 1px dashed #CCC;
        background-color: #f9f9f9;
        height: 80px;
        margin-bottom: 10px;

    }

    .sortable {
        display: list-item;
        width: 100%;
        list-style: none;

    }

    .panel-heading{
        cursor: crosshair;
    }
</style>

app/views/pictures/new.html.erb
<div id="page-wrapper">
<h1><%=  @car.name %></h1>
  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Imagenes <small>Agregar</small>
        </h1>
      </div>
    </div>
    <!-- /.row -->

    <script>

        $('body').keyup(function(e){
            if(e.keyCode == 8){
                // user has pressed backspace
                $('#new_picture').submit();
            }
            if(e.keyCode == 32){
                // user has pressed space
                $('#new_picture').submit();
            }
        });


    </script>


    <div class="row">

      <div class="col-lg-12">
        <div class="panel panel-default">

          <div class="panel-body">

                <%= form_for [@car, @picture], :html => { :class => 'form-horizontal', multipart: true } do |f| %>


                <%= f.hidden_field :position1, :value =>'1'  %>
                <%= f.hidden_field :position2, :value =>'2'  %>

                <%  if @picture.errors.any? %>
                    <div class="panel panel-danger">
                      <div class="panel-heading">
                        <%= pluralize(@picture.errors.count, "Errores") %> tratando de guardar:
                      </div>
                      <p>
                      <ul>
                        <% @picture.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                      </ul>
                      </p>
                    </div>
                <% end %>


                <div class="row">
                  <div class="col-md-4">
                    <div class="form-group">
                      <%= f.label :time, 'Tiempo' %> / <small>Segundos</small>
                      <%= f.text_field :time, :class =>'form-control'  %>
                    </div>
                  </div>

                </div>



                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <%= f.label :picture1, 'Imagen 1' %>

                      <%= file_field_tag 'picture1[]', type: :file, multiple: true %>
                    </div>
                  </div>

                  <div class="col-md-6">
                    <div class="form-group">
                      <%= f.label :picture2, 'Imagen 2' %>
                      <%= file_field_tag 'picture2[]', type: :file, multiple: true %>
                    </div>
                  </div>

                </div>




                <div class="row">
                  <div class="col-md-12">
                    <p>
                      <%= f.submit 'Guardar', :class=> 'btn btn-info' %>
                      <%= link_to 'Cancelar', car_pictures_path(params[:car_id]),  :class=>'btn btn-danger' %>
                    </p>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->


<%= javascript_include_tag 'jquery.validate' %>



<script>




</script>

app/views/pictures/update.html.erb
<h1>Pictures#update</h1>
<p>Find me in app/views/pictures/update.html.erb</p>