config/routes.rb
Rails.application.routes.draw do

  get 'generals/index'

  get 'generals/edit'

  get 'generals/update'

  devise_for :users

  root  'pages#index'
  get 'consulta/:id' => 'pages#consulta'
  resources :cars do
    resources :pictures
  end

  get 'pictures/sort' => 'pictures#sort'

  resources :generals

end

app/models/general.rb
class General < ActiveRecord::Base



end

app/controllers/generals_controller.rb
class GeneralsController < ApplicationController
  def index
      @generals = General.all
  end

  def new
    @generals = General.new
  end


  def create

    @generals = General.new(allowed_params)
    if @generals.save
      redirect_to generals_path
    else
      render 'new'
    end


  end



  def edit
    @generals = General.find(params[:id])
  end

  def update

    @generals = General.find(params[:id])
    if @generals.update_attributes(allowed_params)
      flash[:notice] = 'Información actualizada correctamente'
      redirect_to generals_path
    else
      render 'new'
    end


  end


  private
  def allowed_params
    params.require(:general).permit(:value)
  end
end

app/helpers/generals_helper.rb
module GeneralsHelper
end

app/views/generals/edit.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Vehiculos <small>Agregar</small>
        </h1>
      </div>
    </div>
    <!-- /.row -->




    <div class="row">

      <div class="col-lg-12">
        <div class="panel panel-default">

          <div class="panel-body">
            <%= form_for @generals do |f|  %>

                <%  if @generals.errors.any? %>
                    <div class="panel panel-danger">
                      <div class="panel-heading">
                        <%= pluralize(@general.errors.count, "Errores") %> tratando de guardar:
                      </div>
                      <p>
                      <ul>
                        <% @generals.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                      </ul>
                      </p>
                    </div>
                <% end %>


                <div class="row">
                  <div class="col-md-4">


                    <div class="form-group">
                      <%= f.label :value, 'Segundos' %>
                      <%= f.text_field :value, :class =>'form-control required'  %>
                    </div>


                  </div>
                </div>



                <%= javascript_include_tag 'jquery.validate' %>
                <script>


                    var ready;
                    ready = function() {
                        $("#general_value").validate();
                    };

                    $(document).ready(ready);
                    $(document).on('page:load', ready);


                </script>


                <div class="row">
                  <div class="col-md-12">
                    <p>
                      <%= f.submit 'Guardar', :class=> 'btn btn-info' %>
                      <%= link_to 'Cancelar', generals_path,  :class=>'btn btn-danger' %>
                    </p>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->

app/views/generals/index.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Dashboard <small>Statistics Overview</small>
        </h1>
        <ol class="breadcrumb">
          <li class="active">
            <i class="fa fa-dashboard"></i> Dashboard
          </li>
        </ol>
      </div>
    </div>
    <!-- /.row -->





    <% if flash[:notice] %>
        <div class="row">
          <div class="col-lg-12">
            <div class="alert alert-info alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= flash[:notice] %>
            </div>
          </div>
        </div>
    <% end %>

    <div class="row">

      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-car fa-fw"></i>Vehiculos</h3>
          </div>
          <div class="panel-body">

            <table class="table">
              <%  @generals.each do |item|  %>
                  <tr>
                    <td>
                      <%= item.id %>
                    </td>
                    <td>
                      <%= item.key %>
                    </td>

                    <td>
                      <%= item.value %>''
                    </td>


                    <td>
                      <%= link_to 'Editar', edit_general_path(item.id), :class=>'btn btn-info' %>

                    </td>
                  </tr>
              <% end %>
            </table>
          </div>
        </div>
      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->

app/views/generals/new.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Vehiculos <small>Agregar</small>
        </h1>
      </div>
    </div>
    <!-- /.row -->




    <div class="row">

      <div class="col-lg-12">
        <div class="panel panel-default">

          <div class="panel-body">
            <%= form_for @generals do |f|  %>

                <%  if @generals.errors.any? %>
                    <div class="panel panel-danger">
                      <div class="panel-heading">
                        <%= pluralize(@general.errors.count, "Errores") %> tratando de guardar:
                      </div>
                      <p>
                      <ul>
                        <% @generals.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                      </ul>
                      </p>
                    </div>
                <% end %>


                <div class="row">
                  <div class="col-md-4">


                    <div class="form-group">
                      <%= f.label :value, 'Nombre' %>
                      <%= f.text_field :value, :class =>'form-control required'  %>
                    </div>


                  </div>
                </div>





                <div class="row">
                  <div class="col-md-12">
                    <p>
                      <%= f.submit 'Guardar', :class=> 'btn btn-info' %>
                      <%= link_to 'Cancelar', generals_path,  :class=>'btn btn-danger' %>
                    </p>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->

app/views/generals/update.html.erb
<h1>Generals#update</h1>
<p>Find me in app/views/generals/update.html.erb</p>