config/routes.rb
Rails.application.routes.draw do

  get 'generals/index'

  get 'generals/edit'

  get 'generals/update'

  devise_for :users

  root  'pages#index'
  get 'consulta/:id' => 'pages#consulta'
  resources :cars do
    resources :pictures
  end

  get 'pictures/sort' => 'pictures#sort'

  resources :generals

end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :pictures, dependent: :destroy

  HUMANIZED_ATTRIBUTES = {
      :name => 'Nombre',
      :code => 'Codigo',
  }

  def self.human_attribute_name(attr, options = {})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end



  validates :name, presence: true
  validates :code, presence: true
  default_scope { order('id desc') }



end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!
  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def show
  end

  def edit
    @car = Car.find(params[:id])
  end

  def create

    @car = Car.new(allowed_params)
    if @car.save
      redirect_to cars_path
    else
      render 'new'
    end


  end

  def update

    @car = Car.find(params[:id])

    if @car.update_attributes(allowed_params)
      flash[:notice] = 'Información actualizada correctamente'
      redirect_to cars_path
    else
      render 'new'
    end



  end

  def destroy

    @car = Car.find(params[:id])
    if @car.destroy
      flash[:notice] = 'Información eliminada correctamente'
      redirect_to cars_path
    else
      render 'new'
    end



  end

  private
  def allowed_params
    params.require(:car).permit(:name, :code)
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/create.html.erb
<h1>Car#create</h1>
<p>Find me in app/views/car/create.html.erb</p>

app/views/cars/destroy.html.erb
<h1>Car#destroy</h1>
<p>Find me in app/views/car/destroy.html.erb</p>

app/views/cars/edit.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Vehiculos <small>Agregar</small>
        </h1>
      </div>
    </div>
    <!-- /.row -->




    <div class="row">

      <div class="col-lg-12">
        <div class="panel panel-default">

          <div class="panel-body">
            <%= form_for @car do |f|  %>

                <%  if @car.errors.any? %>
                    <div class="panel panel-danger">
                      <div class="panel-heading">
                        <%= pluralize(@car.errors.count, "Errores") %> tratando de guardar:
                      </div>
                      <p>
                      <ul>
                        <% @car.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                      </ul>
                      </p>
                    </div>
                <% end %>


                <div class="row">
                  <div class="col-md-4">


                    <div class="form-group">
                      <%= f.label :name, 'Nombre' %>
                      <%= f.text_field :name, :class =>'form-control required'  %>
                    </div>


                  </div>

                  <div class="col-md-4">
                    <div class="form-group">
                      <%= f.label :code, 'Codigo' %>
                      <%= f.text_field :code, :class =>'form-control required'  %>
                    </div>
                  </div>

                </div>





                <div class="row">
                  <div class="col-md-12">
                    <p>
                      <%= f.submit 'Guardar', :class=> 'btn btn-info' %>
                      <%= link_to 'Cancelar', cars_path,  :class=>'btn btn-danger' %>
                    </p>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->


<script src="http://jqueryvalidation.org/files/dist/jquery.validate.js"c></script>
<script src="http://jqueryvalidation.org/files/dist/additional-methods.js"></script>

<script>
    $(document).ready(function() {
        $(".edit_car").validate();
    });
</script>

app/views/cars/index.html.erb
<div id="page-wrapper">

<div class="container-fluid">

<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Administrador <small>Vehiculos</small>

    </h1>

  </div>
</div>
<!-- /.row -->





  <% if flash[:notice] %>
      <div class="row">
        <div class="col-lg-12">
          <div class="alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= flash[:notice] %>
          </div>
        </div>
      </div>
  <% end %>

<div class="row">

  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-car fa-fw"></i>Vehiculos</h3>
      </div>
      <div class="panel-body">
        <p>

          <%= link_to 'Agregar Vehiculo', new_car_path,  :class=>'btn btn-info' %>
        </p>
            <table class="table">
              <%  @cars.each do |item|  %>
                <tr>
                  <td>
                    <%= item.id %>
                  </td>
                  <td>
                    <%= item.name %>
                  </td>

                  <td>
                    <%= item.code %>
                  </td>
                  <td>
                    <%= link_to 'Editar', edit_car_path(item.id), :class=>'btn btn-info' %>

                    <%= link_to 'Imagenes', car_pictures_path(item.id), :class=>'btn btn-warning' %>

                    <%= link_to 'Eliminar', {:controller => 'cars', :action => 'destroy', :id => item.id}, :data => {:confirm => 'Estas seguro de eliminar este elemento?'}, :method => :delete, :class=>'btn btn-danger' %>



                  </td>
                </tr>
               <% end %>
            </table>
      </div>
    </div>
  </div>

</div>
<!-- /.row -->

</div>
<!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->

app/views/cars/new.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Vehiculos <small>Agregar</small>
        </h1>
      </div>
    </div>
    <!-- /.row -->




    <div class="row">

      <div class="col-lg-12">
        <div class="panel panel-default">

          <div class="panel-body">
            <%= form_for @car do |f|  %>

            <%  if @car.errors.any? %>
                <div class="panel panel-danger">
                  <div class="panel-heading">
                    <%= pluralize(@car.errors.count, "Errores") %> tratando de guardar:
                  </div>
                  <p>
                  <ul>
                    <% @car.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                  </ul>
                  </p>
                </div>
            <% end %>


            <div class="row">
              <div class="col-md-4">


                <div class="form-group">
                  <%= f.label :name, 'Nombre' %>
                  <%= f.text_field :name, :class =>'form-control required'  %>
                </div>


              </div>

              <div class="col-md-4">


                <div class="form-group">
                  <%= f.label :code, 'Codigo' %>
                  <%= f.text_field :code, :class =>'form-control required'  %>
                </div>


              </div>


            </div>





            <div class="row">
              <div class="col-md-12">
                <p>
                  <%= f.submit 'Guardar', :class=> 'btn btn-info' %>
                  <%= link_to 'Cancelar', cars_path,  :class=>'btn btn-danger' %>
                </p>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->

<script src="http://jqueryvalidation.org/files/dist/jquery.validate.js"c></script>
<script src="http://jqueryvalidation.org/files/dist/additional-methods.js"></script>

<script>
    $(document).ready(function() {
        $("#new_car").validate();
    });
</script>

app/views/cars/show.html.erb
<h1>Car#show</h1>
<p>Find me in app/views/car/show.html.erb</p>

app/views/cars/update.html.erb
<h1>Car#update</h1>
<p>Find me in app/views/car/update.html.erb</p>